config/routes.rb
Rails.application.routes.draw do
  get 'about', to: 'about#index'

  get 'password_resets', to: 'password_resets#new'
  post 'password_resets', to: 'password_resets#create'
  get 'password_resets/edit', to: 'password_resets#edit'
  patch 'password_resets/edit', to: 'password_resets#update'

  get 'password/edit', to: 'password#edit', as: :edit_password
  patch 'password', to: 'password#update', as: :update_password

  get 'sign_up', to: 'registration#new'
  post 'sign_up', to: 'registration#create'

  delete 'sign_out', to: 'session#destroy'
  get 'sign_in', to: 'session#new'
  post 'sign_in', to: 'session#create'

  get 'auth/twitter/callback', to: 'omniauth_callback#twitter'

  resources :twitter_accounts
  resources :tweets

  root 'main#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :twitter_account

  validates :body, length: { minimum: 1, maximum: 280 }
  validates :publish_at, presence: true

  after_initialize do
    self.publish_at ||= 24.hours.from_now
  end

  def published?
    tweet_id?
  end

  def publish_to_tweeter!
    tweet = twitter_account.client.update(body)
    update(tweet_id: tweet.id)
  end
end

app/models/twitter_account.rb
class TwitterAccount < ApplicationRecord
  has_many :tweets
  belongs_to :user

  validates :username, uniqueness: true

  def client
    Twitter::REST::Client.new do |config|
      config.consumer_key        = Rails.application.credentials.dig(:twitter, :api_key)
      config.consumer_secret     = Rails.application.credentials.dig(:twitter, :api_secret)
      config.access_token        = token
      config.access_token_secret = secret
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :twitter_accounts
  has_many :tweets
  has_secure_password

  validates :email, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    session_user_id = session[:user_id]

    return unless session_user_id

    Current.user = User.find_by(id: session_user_id)
  end

  def require_user_logged_in!
    return if Current.user.present?

    redirect_to sign_in_path, alert: 'You must to be sign in to access this content'
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @user = Current.user
  end
end

app/controllers/password_controller.rb
class PasswordController < ApplicationController
  before_action :require_user_logged_in!

  def edit
    @user = Current.user
  end

  def update
    if Current.user.update(password_params)
      redirect_to root_path, notice: 'Password updated successfully'
    else
      render :edit, status: :bad_request
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(email: params[:email])

    PasswordMailer.with(user: @user).reset.deliver_now if @user.present?

    redirect_to root_path,
                notice: 'If an account with that email was found, we have sent a link to reset your password.'
  end

  def edit
    @user = User.find_signed!(params[:token], purpose: 'password_reset')
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to sign_in_path, alert: 'Your token has expired, please try again.'
  end

  def update
    @user = User.find_signed!(params[:token], purpose: 'password_reset')

    if @user.update(password_params)
      redirect_to sign_in_path, notice: 'You password was reset successfully. Please, sign in.'
    else
      render :edit, status: :bad_request
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Successfully created account'
    else
      render :new, status: :bad_request
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:email])

    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id

      redirect_to root_path, notice: 'Logged in successfully'
    else
      flash.now[:alert] = 'Invalid email or password'

      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil

    redirect_to root_path, notice: 'Logged out'
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :require_user_logged_in!
  before_action :set_tweet, only: %i[show edit update destroy]

  def index
    @tweets = Current.user.tweets
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Current.user.tweets.new(tweet_params)

    if @tweet.save
      redirect_to @tweet, notice: 'Tweet Scheduled successfully'
    else
      render :new, status: :bad_request
    end
  end

  def edit; end

  def update
    if @tweet.update(tweet_params)
      redirect_to tweets_path, notice: 'Tweet was updated successfully'
    else
      render :edit, status: :bad_request
    end
  end

  def destroy
    @tweet.destroy
    redirect_to tweets_path, notice: 'Tweet was unscheduled'
  end

  private

  def tweet_params
    puts params[:tweet]
    params.require(:tweet).permit(:twitter_account_id, :body, :publish_at)
  end

  def set_tweet
    @tweet = Current.user.tweets.find_by(id: params[:id])
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/omniauth_callback_helper.rb
module OmniauthCallbackHelper
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/twitter_accounts_helper.rb
module TwitterAccountsHelper
end

app/views/tweets/_form.html.erb
<%= form_with model: tweet do |form| %>
  <%= render "shared/form_error_messages", form: form %>

  <div class="mb-3">
    <%= form.label :twitter_account_id %>
    <%= form.collection_select :twitter_account_id, Current.user.twitter_accounts, :id, :username, {}, { class: "form-control" } %>
    <%# <%= button_to "Connect twitter account", "/auth/twitter", method: :post, class: "btn btn-primary mt-3" %>
  </div>

  <div class="mb-3">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :publish_at %>
    <div class="mb-3">
      <%= form.datetime_select :publish_at, class: "form-control" %>
    </div>
  </div>

  <%= form.button "Schedule", class: "btn btn-primary" %>
   <% if form.object.persisted? %>
    <%= link_to "Delete", form.object, method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you Sure?" }, class: "btn btn-outline-danger" %>
  <% end %>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="mb-3 card card-body">
  <%= tweet.body %>
  <div class="me-4">
    <%= image_tag tweet.twitter_account.image, class: "rounded-circle" %>
    <%= link_to "@#{tweet.twitter_account.username}", "https://twitter.com/#{tweet.twitter_account.username}", target: :_blank %>

    <% if tweet.published? %>
      <%= link_to "View Tweet", "https://twitter.com/#{tweet.twitter_account.username}/status/#{tweet.tweet_id}", target: :_blank %>
    <% else %>
      Scheduled for <%= l tweet.publish_at, format: :long %>
      <%= link_to "Edit Tweet", edit_tweet_path(tweet) %>
    <% end %>
  </div>
</div>

app/views/tweets/edit.html.erb
<h1>Edit Tweet</h1>

<%= render "form", tweet: @tweet %>

app/views/tweets/index.html.erb
<div class="d-flex align-items-center justify-content-between">
  <h1>Tweets</h1>
  <% if Current.user.twitter_accounts.any? %>
    <%= link_to "Schedule tweets", new_tweet_path, class: "btn btn-primary" %>
  <% end %>
</div>

<% if Current.user.twitter_accounts.none? %>
  <%= button_to "Connect twitter account", "/auth/twitter", method: :post, :data => {turbo: "false"}, class: "btn btn-primary" %>
<% end %>


<%= render @tweets %>

app/views/tweets/new.html.erb
<h1>Schedule a Tweet!</h1>

<%= render "form", tweet: @tweet %>